# Not http context block as this file will be included into the nginx.conf file
server {

    listen 80;

    # The PHP-FPM Server (Symfony API)
    location ~ ^/api {
        alias /var/www/e_commerce/public/; 

        fastcgi_pass php_fpm:9000; # The server address

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/e_commerce/public/index.php; 
    }

    location / {
        # the file the react app is mounted on   
        root /var/www/e_commerce/; 
        try_files $uri /index.html;
    }

    error_log /var/log/nginx/api_error.log;
    access_log /var/log/nginx/api_access.log;
}
