http {

    server {

        listen # nginx_network:nginx_port ;

        # The PHP-FPM Server (Symfony API)
        location ~ ^/api/ {

            fastcgi_pass # php_fpm localhost:9000;
        }

        location / {
            
        }
    }

}